### ISSUE TITLE
top100才显示10条,应该显示更多才对啊

### ISSUE THREAD

**Issue by xxssww0258** [awesomes-cn/new-awesomes#2]

**Comment by bimohxh** [comment]
@xxssww0258  谢谢提醒，已经改过来了，刚刚上线新版还有很多bug，欢迎多提提

**Comment by xxssww0258** [comment]
我建议在页脚加个“更多”每点一下，再加三十条，你觉得怎样？为了突显top100这个词，后面的应该换一种色调，突显出这是top100外的

**Comment by bimohxh** [comment]
@xxssww0258 这个其实倒没多大意义，如果能看所有的也不能突出我们top100这个主题了

**Comment by xxssww0258** [comment]
@bimohxh 
如果只用于观看排名的确是没有意义，但是如果是想浏览更多准备的挤进排名新框架，新技术是有一定的作用存在

**Comment by bimohxh** [comment]
@xxssww0258  谢谢建议，我们考虑一下
