### ISSUE TITLE
新版首页辨识度不高

### ISSUE THREAD

**Issue by ghost** [awesomes-cn/new-awesomes#3]
首页的推荐感觉颜色太淡了，鼠标悬浮上去确实很显眼，但是不悬浮的时候就是灰蒙蒙的一片

**Comment by bimohxh** [comment]
@lzq920  是这样的，本身我们是想在首页弱化其它内容，突出搜索的，所以把下面那一块虚化了

**Comment by ghost** [comment]
这种弱化也是没谁了，哈哈。。。

**Comment by bimohxh** [comment]
@lzq920 设计能力有限，哈哈，想到好的方案就替换掉
