### ISSUE TITLE
网站专题自动滚动bug

### ISSUE THREAD

**Issue by zhangfugui727** [awesomes-cn/new-awesomes#6]
首先还是感谢一下良心网站的作者。
https://www.awesomes.cn/网站
路径：专题模块
详情：
1、库数量统计信息错误。
2、屏幕移至专题某项时，由于自动滚动定位，导致信息无法查看。如vue部分，有的分类条目较少，滚动至该处后，其他条目也处于激活状态，然后强制滚动到激活条目，依次往复，造成数量较少分类信息查看较困难。

**Comment by bimohxh** [comment]
谢谢反馈，数量是错的，这个会改正

不过第2点有点不太清楚，为了性能，目前是在页面滚动过程中不会计算，滚动完成后才会去计算左侧菜单栏的激活状态

**Comment by zhangfugui727** [comment]
这个确实不好描述。
![qq 20170828143036](https://user-images.githubusercontent.com/30425581/29761774-7bdb7a98-8bfd-11e7-85fc-e8af2aa3ccd2.png)
环境：firefox55出现以下bug，且ie10中左侧分类不能点击
如图：当在vue专题中，字体、通知提示2项条目较少，都只有一条。在firefox中，点击字体项，页面会多次滚动，自动定位到加载进度。

**Comment by zhangfugui727** [comment]
如果是部分浏览器的原因，我能够克服，怕打扰各位。

**Comment by bimohxh** [comment]
@gitzhangfugui 没有打扰哈，感谢反馈。因为Awesomes系列网站主要针对的就是Chrome浏览器，其它浏览器没有进行多少测试，接下来我们会针对主流的浏览器都测试一下，找找bug

**Comment by zhangfugui727** [comment]
@bimohxh 嗯 谢谢！我能问问你们数据怎么和github同步的吗？是通过接口，还是人为干预？还有就是怎么给github项目分类的，现在github通过关键标签，我觉得你们这个特赞。找库都很方便。

**Comment by bimohxh** [comment]
@gitzhangfugui  数据同步是调用的GitHub开放的接口，做成定时任务。
关于分类这一块其实是需要人为去分类的，还做不到自动分类，这也是Awesomes.cn的特色吧，未来可能会考虑加入程序分析，目前每日的的更新都是定时任务自动获取最新的3条数据，翻译是走的百度翻译API，结果是不准确，需要修正，所以目前部分数据信息还是得人去做才行。这些都可以参阅我们的源码

**Comment by zhangfugui727** [comment]
@bimohxh 谢谢，有时间会去研究的，最近比较忙，期待新功能！
